### PR TITLE
Articles Tests Bearer -> Token

### PR DESCRIPTION
**Pull request by guillaumemaka**

### CODE REVIEW

**Comment by JackyChiu** [comment]
Can you look into fixing this git issue? Try:
On your `articles_feature` branch,
```
git fetch
git rebase upstream/master
# fix conflicts if any
git push origin articles_feature 
# use the -f flag if a regular push doesn't work
```

**Comment by guillaumemaka** [comment]
I did what you ask

**Comment by JackyChiu** [comment]
RIP man idk why this keeps happening

**Comment by guillaumemaka** [comment]
What ? the long list of commit ?

**Pull request closed without merging**
